### ISSUE TITLE
Consider excluding markdown

### ISSUE THREAD

**Issue by chmurph2** [glennr/uber-glory-tmbundle#1]
Two trailing spaces in markdown is a line break.  I added the following to your "Convert Tabs to Spaces, Strip Whitespace, Save" macro to resolve this:

-text.html.markdown

-Chris

**Comment by ma11hew28** [comment]
Thanks, Chris! I wanted to exclude markdown as well and finally figured this out. Here are more detailed instructions:
http://stackoverflow.com/questions/4364415/exclude-file-type-from-textmate-bundle-macros/4364838#4364838

**Comment by chmurph2** [comment]
Sure, no problem.

**Comment by ma11hew28** [comment]
Thanks!

**Comment by glennr** [comment]
Cheers guys. This is now fixed in a935345dacbf83958fe40b5d6d12a453f3a161e4
