### ISSUE TITLE
Consider excluding blank lines

### ISSUE THREAD

**Issue by ankit** [glennr/uber-glory-tmbundle#5]
Textmate automatically indents the new line with Tab spaces when Enter is pressed. When collaborating with someone else who doesn't use this bundle, it can cause a series of whitespace changes to show in the diff.

So, maybe it shouldn't trim blank lines?

Case in point: https://github.com/ankit/stylebot/commit/5700711215296992e62400daa64cbe9a934626d0#commitcomment-386556 :)

**Comment by glennr** [comment]
Hi Ankit,

Agreed. Seems like a good idea.

Won't have a chance to look at it til next week though. Patches welcome :-)

Cheers

Glenn

**Comment by glennr** [comment]
see https://github.com/glennr/uber-glory-tmbundle/pull/6
